# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tfstatecontainer"
    key                  = "./terraform.tfstate"
    resource_group_name  = "tfstate-rg"
    storage_account_name = "2023tfstatestorage"
  }
}
