name: Terraform Module CI

on:
  push:
    branches:
      - master

jobs:
  terraform-modules:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
        shell: bash

    needs: [terraform-lint, terrascan]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Find Terraform modules
      id: find_modules
      run: |
            # Find all directories under the "terraform" folder in the repository
            find ./terraform/* -type d > modules.txt
            echo "::set-output name=modules::$(cat modules.txt)"

          
    - name: Iterate through Terraform modules
      run: |
            # Read the output variable from the previous step
            file="modules.txt"

            # While loop to iterate through entire terraform directory
            while IFS= read -r line
            do
                module_name=$(basename $line)

                echo "-----------------------------------"

                echo "Processing module $module_name"
                cd $line

                echo "Initializing Terraform..."
                terraform init

                echo "Validating Terraform..."
                terraform validate

                echo "Formatting Terraform..."
                terraform fmt -check

                echo "Success! $module_name is OK."
                echo "-----------------------------------"
                cd ../..
            done <"$file"

    # - name: Create Plan files
    #   run: |
    #         # Read the output variable from the previous step
    #         file="modules.txt"

    #         # While loop to iterate through entire terraform directory
    #         while IFS= read -r line
    #         do
    #             module_name=$(basename $line)

    #             echo "-----------------------------------"

    #             echo "Processing module $module_name"
    #             cd $line

    #             echo "Creating Plan file..."
    #             terraform plan -out=$(module_name)-plan.tfplan

    #             echo "Success! $module_name planned."
    #             echo "-----------------------------------"
    #             cd ../..
    #         done <"$file"
      
        
  terraform-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
        shell: bash

    steps:
    - name: Run tflint
      uses: devops-infra/action-tflint@v0.3
      with:
        dir_filter: terraform/*/

  terrascan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Terrascan IaC scanner
      uses: tenable/terrascan-action@v1.3.0
      with:
        iac_type: terraform
        iac_dir: terraform/
        iac_version: v14
        policy_type: azure
        only_warn: true
        sarif_upload: true

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: terrascan.sarif
      
            